<?php
/**
 * @var $block \PHPStudios\ForceLogin\Block\Account\AuthorizationLink
 * @var $escaper \Magento\Framework\Escaper
 */
$escaper = $block->getEscaper();

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link" data-label="<?= ($block->isEnableRegister() && $block->isEnable()) ? '' : $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <?= $escaper->escapeHtml($block->getLabel()) ?>
    </a>
</li>
